FROM almalinux
LABEL maintainer="Ghouse Rizvi <ghouserizvi@gmail.com>"
LABEL description="This is a simple Dockerfile to install Nginx on AlmaLinux"
LABEL version="1.0"
LABEL Author="Ghouse Rizvi"\
    TOPIC="Dockerfile, AlmaLinux, Nginx, Web Server"\
    LICENSE="MIT License"\
    DURATION="25 HRS"