FROM alpine
#CMD ["ping","-c","5","8.8.8.8"]
#ENTRYPOINT ["ping","-c","5","8.8.8.8"]
CMD ["8.8.8.8"]
#CMD can be used to pass arguments to ENTRYPOINT. In this case, CMD is passing the argument "8.8.8.8"
ENTRYPOINT ["ping","-c","5"] 