FROM almalinux
RUN dnf -y install nginx unzip && dnf clean all && \
    mkdir -p /usr/share/nginx/html

# ADD will download the URL at build time
ADD https://www.tooplate.com/zip-templates/2143_inner_peace.zip template.zip

RUN unzip template.zip -d /usr/share/nginx/html \
    && rm -f template.zip

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
