FROM almalinux
RUN yum install nginx zip unzip -y 
RUN mkdir -p webfile
RUN cd webfile
ADD https://www.tooplate.com/zip-templates/2143_inner_peace.zip /webfile/
RUN unzip /webfile/2143_inner_peace.zip -d /usr/share/nginx/html/
EXPOSE 80
CMD [ "nginx","-g","daemon off;" ]
