FROM almalinux:9
RUN yum install nginx -y #ensure nginx is installed and run execute at the time of image creation
CMD [ "nginx","-g","daemon off" ] # Keeps nginx running in the foreground when the container starts