FROM almalinux:9
RUN yum install nginx -y && yum clean all && rm -rf /var/cache/yum #ensure nginx is installed and clean up cache
CMD [ "nginx","-g","daemon off" ] # Keeps nginx running in the foreground so the container stays alive.ts