FROM almalinux
ENV NGINX_VERSION=1.20.1 \ 
    NGINX_USER=nginx \
    NGINX_GROUP=nginx \
    NGINX_HOME=/var/lib/nginx \
    NGINX_LOG_DIR=/var/log/nginx \
    NGINX_CONF_DIR=/etc/nginx \
    NGINX_SBIN=/usr/sbin/nginx \
    NGINX_PID_FILE=/var/run/nginx.pid \
    NGINX_DEFAULT_CONF=$NGINX_CONF_DIR/conf.d/default.conf
    